// Generated by Selenium IDE
import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import static org.openqa.selenium.devtools.v112.page.Page.navigate;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.FluentWait;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;

import java.time.Duration;
import java.util.*;
import java.util.concurrent.TimeUnit;


public class UntitledTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    WebDriverManager.chromedriver().setup();
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void untitled() throws InterruptedException {
	    driver.get("https://www.naver.com/");
	    Thread.sleep(1000);	    
	    driver.manage().window().setSize(new Dimension(1289, 962));
	    {
	      WebElement element = driver.findElement(By.cssSelector(".MediaSubscriptionView-module__subscription_box___YshKW:nth-child(6) > .MediaSubscriptionView-module__news_thumb___UDmow"));
	      Actions builder = new Actions(driver);
	      builder.moveToElement(element).perform();
	    }
	    Thread.sleep(1000);
	    {
	      WebElement element = driver.findElement(By.tagName("body"));
	      Actions builder = new Actions(driver);
	      builder.moveToElement(element, 0, 0).perform();
	    }
	    Thread.sleep(1000);
	    driver.findElement(By.linkText("스포츠")).click();
	    Thread.sleep(1000);
	    js.executeScript("window.scrollTo(0,289)");
	    Thread.sleep(1000);
	    vars.put("window_handles", driver.getWindowHandles());
	    Thread.sleep(1000);
	    driver.findElement(By.linkText("배지환 \'3G 연속 안타→5번째 도루 실패\', 간파 당한 타이밍 어쩌나... 3-4 역전패라 더 아쉽다 [PIT 리뷰]")).click();
	    Thread.sleep(1000);
	    driver.close();
  }

}
